---
abstract: 'modules for working with Atom feeds'
author:
  - unknown
build_requires:
  Test::Exception: 0
  Test::More: 0
configure_requires:
  Module::Build: 0.40
dynamic_config: 1
generated_by: 'Module::Build version 0.4003, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Catmandu-Atom
provides:
  Catmandu::Atom:
    file: lib/Catmandu/Atom.pm
    version: 0.02
  Catmandu::Exporter::Atom:
    file: lib/Catmandu/Exporter/Atom.pm
    version: 0
  Catmandu::Importer::Atom:
    file: lib/Catmandu/Importer/Atom.pm
    version: 0
requires:
  Catmandu: 0.2003
  XML::Atom: 0.41
  namespace::clean: 0.24
  perl: v5.10.1
resources:
  license: http://dev.perl.org/licenses/
version: 0.02
